#!/bin/bash

alias make='make_func'
make_func() { 
	if [[ $PWD == *"<PATH TO UVA TOP FOLDER>"* ]]; then
		echo "Making using UVa makefile"
		/usr/bin/make -f ~<PATH TO MAKE FILE> $*
	else
		/usr/bin/make $*
	fi
}

export PATH="$PATH:< PATH TO FOLDER CONTAINING >"
source mark
