#!/bin/bash
#  marker v1.0.1
# 
#  Copyright (c) 2015 Marcus Karpoff <marcuskarpoff@gmail.com>
#  
#  Permission to use, copy, modify, and distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#  
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#  ANY SPECIAL, DIRLISTECT, INDIRLISTECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#  
VERSION="
mark1.0.1 
Copyright (c) 2015 Marcus Karpoff
Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

Written by Marcus Karpoff.
"
USE_N=0
USE_T=0
USE_S=0
DIRLIST=
TTAG=".trivial.tag"
NTAG=".non-tri.tag"
STAG=".solved.tag"

while [[ "$1" != "" ]]; do
	if [[ "$1" == "-"* ]]; then
		while getopts "NTSnts" opt; do
			case "$opt" in
			n | N)
				USE_N=1;;
			t | T) 
				USE_T=1;;
			s | S)
				USE_S=1;;
			v)
				printf "$VERSION"
				exit
				;;
			esac
		done
		shift
	else
		DIRLIST=${DIRLIST}"$1 "
		shift
	fi
done

if [[ $DIRLIST == "" ]]; then
	$DIRLIST="./"
fi

for DIR in $DIRLIST; do
	case ${DIR} in
		*/) DIR=$DIR;;
		*) DIR=$DIR/;;
	esac
	if [ -d $DIR ]; then
		if (( USE_N == 1 )); then
			if [ -f $DIR$NTAG ]; then
				rm $DIR$NTAG
			else
				touch $DIR$NTAG
			fi
		fi
		if (( USE_T == 1 )); then
			if [ -f $DIR$TTAG ]; then
				rm $DIR$TTAG
			else
				touch $DIR$TTAG
			fi
		fi
		if (( USE_S == 1 )); then
			if [ -f $DIR$STAG ]; then
				rm $DIR$STAG
			else
				touch $DIR$STAG
			fi
		fi
	fi
done
	
