#!/bin/bash
#  tester v2.2.1
#  
#  Copyright (c) 2015 Marcus Karpoff <marcuskarpoff@gmail.com>
#  
#  Permission to use, copy, modify, and distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#  
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#  
Input=TestFiles/Input/
Output=TestFiles/Output/

TESTBREAK="================================================\n"

	RED='\033[1;31m'          # Red
	GREEN='\033[1;32m'        # Green
	ORANGE='\033[0;33m'       # Yellow
	BLUE='\033[1;34m'         # Blue
	PURPLE='\033[0;35m'       # Purple
	CYAN='\033[1;36m'         # Cyan
	WHITE='\033[0;37m'  

if [[ $1 == "" ]]; then
	EXE="ans"
	ALL=0
elif [[ $1 == "--all" ]]; then
	ALL=1
	if [[ $2 == "" ]]; then
		EXE="ans"
	else
		EXE=$2
	fi
else
	EXE=$1
	if [[ $2 == "" ]]; then
		ALL=0
	else
		ALL=1
	fi
fi

if [ ! -f $EXE ]; then
	printf "${RED}No program named (${BLUE} $EXE ${RED}) found${WHITE}\n"
	exit
fi
if [ ! -d $Input ]; then
	printf "${RED}No input folder named (${BLUE} TestFiles/Input/ ${RED})${WHITE}\n"
	exit
fi
if [ ! -d $Output ]; then
	printf "${RED}No output folder named (${BLUE} TestFiles/Output/ ${RED})${WHITE}\n"
	exit
fi


printf "Program:${BLUE} $EXE${WHITE}\n"
DIFFPROG=$(command -v colordiff)
if [ "$DIFFPROG" == "" ];	then
	DIFFPROG=diff
fi
NUMTESTS=$(ls TestFiles/Input/ | wc -l)
printf "Num tests: ${RED}$NUMTESTS${WHITE}\n"
for f in $(ls $Input); do
		printf "$TESTBREAK"
		TIMEFORMAT='%3R'
		TIME=$((time( ./$EXE < $Input$f > temp) >&2) 2>&1)
		printf "TEST: ${RED}$f${RED}$WHITE\t"
		if [ ! -f $Output$f ]; then
			printf "${RED}No matching output file for input file (${BLUE} $f ${RED})\n${WHITE}"
		else
			EXP=$Output$f
			DIFF=$(diff temp $EXP)
			LLE=$(wc -L $EXP | awk '{print $1}')
			LLA=$(wc -L temp | awk '{print $1}')
			COL=$LLA
			if [ $LLE -gt $LLA ]; then
				COL=$LLE
			fi
			COLSIZE=$COL
			SBS=1
			if [ $COLSIZE -gt 50 ]; then
				SBS=0
				COLSIZE="`tput cols`"
				COL=$(expr $COLSIZE / 2)
			elif [ $COLSIZE -lt 12 ]; then
				COLSIZE=24
				COL=12
			else
				COLSIZE=$(expr $COL \* 2)
			fi
			pad=$(printf '%0.1s' "-"{1..80})

			if [ "$DIFF" != "" ]; then
				printf "${RED}Failed\t${BLUE}${TIME}s${WHITE}\n"
				printf "${RED}EXPECTED:${WHITE}"
				printf "%*.*s" 0 $((COL - 12 )) "$pad"
				printf "${BLUE}ACTUAL:${WHITE}\n"
				if [ $SBS -eq 1 ]; then
					$DIFFPROG -yW "$COLSIZE" $EXP temp
				else
					$DIFFPROG $EXP temp
				fi
				if [ $ALL -eq 0 ]; then
					rm -f temp
					printf "$TESTBREAK"
					break
				fi
			else
				printf "${GREEN}Passed\t${BLUE}${TIME}s${WHITE}\n"
			fi
		fi
		rm -f temp
done
printf "$TESTBREAK"
